# Generated by Django 4.2.5 on 2023-10-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="bilibili",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField(default=1)),
                ("pic_href", models.CharField(default="", max_length=500)),
                ("title", models.CharField(default="", max_length=500)),
                ("tname", models.CharField(default="", max_length=100)),
                ("link", models.URLField(default="", max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="dektinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("category_url", models.URLField(max_length=100)),
                ("item_id", models.CharField(max_length=100)),
                ("activity_name", models.CharField(max_length=100)),
                ("enroll_start_time", models.DateTimeField()),
                ("enroll_end_time", models.DateTimeField()),
                ("active_start_time", models.DateTimeField()),
                ("active_end_time", models.DateTimeField()),
                ("activity_picurl", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="github",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
                ("href", models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="minhang_24h_weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name_of_weather_picture", models.CharField(max_length=100)),
                ("weather_text", models.CharField(max_length=100)),
                ("temperature", models.CharField(max_length=100)),
                ("wind_direction", models.CharField(max_length=100)),
                ("wind_strength", models.CharField(max_length=100)),
                ("hour", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="seieeNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=100)),
                ("href", models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="weibo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank_pic_href", models.CharField(max_length=500)),
                ("title", models.CharField(max_length=500)),
                ("link", models.URLField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name="zhihu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(default="", max_length=10)),
                ("title", models.CharField(default="", max_length=500)),
                ("href", models.CharField(default="", max_length=500)),
                ("picture_element", models.URLField(default="", max_length=1000)),
            ],
        ),
    ]
