# Generated by Django 4.2.5 on 2023-09-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zhihu',
            name='picture_element',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
