# Generated by Django 4.2.5 on 2023-10-19 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="dektinfo",
        ),
    ]
