# Generated by Django 4.2.5 on 2023-10-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dektinfo",
            name="activity_picurl",
            field=models.TextField(),
        ),
    ]
