# Generated by Django 4.2.5 on 2023-09-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_zhihu_picture_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilibili',
            name='link',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='github',
            name='href',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='weibo',
            name='link',
            field=models.URLField(max_length=10000),
        ),
    ]
