# Generated by Django 4.2.5 on 2023-10-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_delete_dektinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="dektinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("category_url", models.URLField(max_length=100)),
                ("item_id", models.CharField(max_length=100)),
                ("activity_name", models.CharField(max_length=100)),
                ("enroll_start_time", models.DateTimeField()),
                ("enroll_end_time", models.DateTimeField()),
                ("active_start_time", models.DateTimeField()),
                ("active_end_time", models.DateTimeField()),
                ("activity_picurl", models.CharField(max_length=200)),
            ],
        ),
    ]
