# Generated by Django 4.2.5 on 2023-10-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_collection_user_alter_collection_data0_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="data10",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="data9",
            field=models.TextField(blank=True, null=True),
        ),
    ]
