# Generated by Django 4.2.5 on 2023-10-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_dektinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dektinfo",
            name="category_url",
            field=models.URLField(max_length=500),
        ),
    ]
