# Generated by Django 4.2.5 on 2023-10-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_bilibili_link_alter_github_href_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dektinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('item_id', models.CharField(max_length=100)),
                ('activity_name', models.CharField(max_length=100)),
                ('enroll_start_time', models.DateTimeField()),
                ('enroll_end_time', models.DateTimeField()),
                ('active_start_time', models.DateTimeField()),
                ('active_end_time', models.DateTimeField()),
                ('activity_picurl', models.CharField(max_length=200)),
            ],
        ),
    ]
