# Generated by Django 4.2.5 on 2023-10-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_collection_data10_collection_data9"),
    ]

    operations = [
        migrations.CreateModel(
            name="keywords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("type", models.CharField(default="", max_length=50)),
                ("key", models.CharField(max_length=50)),
            ],
        ),
    ]
