# Generated by Django 4.2.5 on 2023-10-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_dektinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='seieeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('href', models.URLField(max_length=100)),
            ],
        ),
    ]
