# Generated by Django 4.2.5 on 2023-10-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_alter_dektinfo_category_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dektinfo",
            name="category_url",
            field=models.URLField(max_length=2000),
        ),
    ]
