# Generated by Django 4.2.5 on 2023-10-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0006_minhang_24h_weather"),
        ("app01", "0009_alter_dektinfo_activity_picurl"),
    ]

    operations = []
