# Generated by Django 4.2.5 on 2023-10-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0010_merge_20231022_1214"),
    ]

    operations = [
        migrations.CreateModel(
            name="collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site", models.CharField(max_length=100)),
                ("data0", models.CharField(blank=True, max_length=100, null=True)),
                ("data1", models.CharField(blank=True, max_length=100, null=True)),
                ("data2", models.CharField(blank=True, max_length=100, null=True)),
                ("data3", models.CharField(blank=True, max_length=100, null=True)),
                ("data4", models.CharField(blank=True, max_length=100, null=True)),
                ("data5", models.CharField(blank=True, max_length=100, null=True)),
                ("data6", models.CharField(blank=True, max_length=100, null=True)),
                ("data7", models.CharField(blank=True, max_length=100, null=True)),
                ("data8", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="dektinfo",
            name="category_url",
            field=models.TextField(default="https://dekt.sjtu.edu.cn/h5/index"),
        ),
        migrations.AlterField(
            model_name="dektinfo",
            name="activity_picurl",
            field=models.TextField(),
        ),
    ]
